### ISSUE TITLE
Questions about novelty

### ISSUE THREAD

**Issue by zhaoguangxiang** [openai/sparse_attention#4]
The paper is will written and make great results in various datasets.
However, the contribution of novelty is unclear.
Q1： How is  the  Sparse Transformer (strided) different from local attention?
Q2： How is  the  Sparse Transformer (fixed) different from block self attention? ( ICLR 2018 https://openreview.net/forum?id=H1cWzoxA-)?

**Comment by nguyenvo09** [comment]
.

**Comment by alphadl** [comment]
seems that the author is busy ~
